{
 "title": "Artifactory Prometheus Exporter",
 "description": "Dashboard for JFrog Artifactory Prometheus exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(artifactory_system_license,instance)"
   },
   {
    "name": "version",
    "label": "version",
    "query": "label_values(artifactory_system_version{instance=~\"$instance\"},version)"
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "License Expires in",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "artifactory_system_license{instance=~\"$instance\"}",
     "group": { "alias": "", "name": "Status Checks", "url": "" },
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Artifactory Health $instance ($version)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "artifactory_system_healthy{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Artifactory Exporter ($instance)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(artifactory_up{instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "Overviewe", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total Used Space by Repo",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 11 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(artifactory_storage_repo_used_bytes) by (package_type,type,name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Filestore Used Space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(artifactory_storage_filestore_used_bytes)"
    }
   ]
  },
  {
   "title": "Total Size of Artifacts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(artifactory_storage_artifacts_size_bytes)"
    }
   ]
  },
  {
   "title": "Number of Local Repositories by type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(artifactory_storage_repo_files{package_type!=\"na\",type=\"local\"}) by (package_type)",
     "legendFormat": "{{package_type}}"
    }
   ]
  },
  {
   "title": "Number of Internal Users",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(artifactory_security_users{realm=\"internal\"})"
    }
   ]
  },
  {
   "title": "Total Number of Artifacts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(artifactory_storage_artifacts)"
    }
   ]
  },
  {
   "title": "Number of SAML Users",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(artifactory_security_users{realm=\"saml\"})"
    }
   ]
  },
  {
   "title": "Repositories Summary",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "max(artifactory_storage_repo_files) by (package_type,type,name)"
    },
    {
     "expr": "max(artifactory_storage_repo_folders) by (package_type,type,name)"
    },
    {
     "expr": "max(artifactory_storage_repo_items) by (package_type,type,name)"
    },
    {
     "expr": "max(artifactory_storage_repo_used_bytes) by (package_type,type,name)"
    },
    {
     "expr": "max(artifactory_storage_repo_percentage) by (package_type,type,name)"
    }
   ]
  },
  {
   "title": "Total Created and Downloaded Artifacts/Minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(max(artifactory_artifacts_created_1m{type=\"local\",name!~\"artifactory-build-info|auto-trashcan\"} > 0) by (name))",
     "legendFormat": "created"
    },
    {
     "expr": "sum(max(artifactory_artifacts_downloaded_1m{type=\"local\",name!~\"artifactory-build-info|auto-trashcan\"} > 0) by (name))",
     "legendFormat": "downloaded"
    }
   ]
  },
  {
   "title": "Downloaded Artifacts/Minute per repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(artifactory_artifacts_downloaded_1m{type=\"local\",name!~\"artifactory-build-info|auto-trashcan\"} > 0) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Created Artifacts/Minute per repo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(artifactory_artifacts_created_1m{type=\"local\",name!~\"artifactory-build-info|auto-trashcan\"} > 0) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}